[package]
name = "boring-3d-tetris"
version = "0.0.1"
edition = "2018"

[dependencies]
anyhow = "^1.0"
reqwest = { version = "^0.11.0", features = ["json"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
tokio = { version = "^1.0", features = ["full"] }
